---
version: 0.2
phases:
  install:
    commands:
      - curl -sS -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.10.3/2018-07-26/bin/linux/amd64/aws-iam-authenticator
      - curl -sS -o kubectl https://amazon-eks.s3-us-west-2.amazonaws.com/1.14.6/2019-08-22/bin/linux/amd64/kubectl
      - chmod +x ./kubectl ./aws-iam-authenticator
      - export PATH=$PWD/:$PATH
      - apt-get update && apt-get -y install jq python3-pip python3-dev && pip3 install --upgrade awscli
      - apt-get install -y software-properties-common
      - add-apt-repository ppa:openjdk-r/ppa
      - apt-get update -y
      - apt-get install -y openjdk-8-jdk
      - apt-get install -y maven
  pre_build:
    commands:
      - cp ./deploy/kubernetes/kube-deploy.yaml .
      - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
      - sed -i 's@promotion:latest@'"promotion:$TAG"'@' kube-deploy.yaml
      - $(aws ecr get-login --no-include-email --region us-east-2)
      - export KUBECONFIG=$HOME/.kube/config
  build:
    commands:
      - ./mvnw clean package
      - docker build --tag=promotion:$TAG .
      - docker tag promotion:$TAG 715977739758.dkr.ecr.us-east-2.amazonaws.com/promotion:$TAG

  post_build:
    commands:
      - $(aws ecr get-login --no-include-email --region us-east-2)
      - docker push 715977739758.dkr.ecr.us-east-2.amazonaws.com/promotion:$TAG
      - CREDENTIALS=$(aws sts assume-role --role-arn $EKS_KUBECTL_ROLE_ARN --role-session-name codebuild-kubectl --duration-seconds 900)
      - export AWS_ACCESS_KEY_ID="$(echo ${CREDENTIALS} | jq -r '.Credentials.AccessKeyId')"
      - export AWS_SECRET_ACCESS_KEY="$(echo ${CREDENTIALS} | jq -r '.Credentials.SecretAccessKey')"
      - export AWS_SESSION_TOKEN="$(echo ${CREDENTIALS} | jq -r '.Credentials.SessionToken')"
      - export AWS_EXPIRATION=$(echo ${CREDENTIALS} | jq -r '.Credentials.Expiration')
      - aws eks update-kubeconfig --name $EKS_CLUSTER_NAME
      - kubectl apply -f kube-deploy.yaml
      - printf '[{"name":"kube-deploy","imageUri":"%s"}]' 715977739758.dkr.ecr.us-east-2.amazonaws.com/promotion:$TAG > build.json
artifacts:
  files: build.json
